#!/bin/sh

if [ "$1" = "-h" ]; then
	echo "Usage: sfetch [-n]"
	exit 0
fi

if [ "$1" = "-n" ]; then
	NARROW=1
else
	if [ "$1" != "" ]; then
		echo "Unknown option $1"
		echo "Run sfetch -h to show all available options"
		exit 1
	fi
fi

var_host=$(hostname)
var_user=$(whoami)
var_uptime=$(uptime -p | sed 's/up //' | sed 's/, / and /')
var_pkgs=$(pacman -Q | wc -l)
var_kernel=$(cat /proc/sys/kernel/osrelease)

if [ "$NARROW" = "1" ]; then
	echo -e "\033[1;35m $var_user\033[0;35m@\033[1;35m$var_host\033[0m:"
	echo -e "\033[0;31m  -\033[0;33m uptime \033[1;33m$var_uptime"
	echo -e "\033[0;31m  -\033[0;33m kernel \033[1;33m$var_kernel"
	echo -e "\033[0;31m  -\033[0;33m installed pkgs \033[1;33m$var_pkgs\033[0m"
else
	echo -e "\033[1;35m $var_user\033[0;35m@\033[1;35m$var_host\033[0m"
	echo -e "\033[0;31m [\033[0;33m uptime\033[1;33m $var_uptime\033[0;33m, kernel \033[1;33m$var_kernel\033[0;33m, \033[1;33m$var_pkgs\033[0;33m pkgs\033[0;31m ]\033[0m"
fi
